---
- name: Install Docker
  hosts: all
  become: yes
  vars:
    CTOP_VERSION: "0.7.3"
    DOCKER_COMPOSE_VERSION: "1.25.1"
    USER: "michaelkora"
    
  
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common','gnupg-agent', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present


    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: add user to group Docker
      command: usermod -a -G docker $USER

- name: Get the server running
  hosts: servers
  become: yes
  tasks:
    - name: copy dockerfile to servers
      copy:
        src: Dockerfile
        dest: $HOME/Dockerfile

    - name: build the docker image
      command: docker build -t mongo-server $HOME 

    - name: run docker
      command: sudo docker run -d -p 27017:27017 mongo-server

